<?php

/**
 * BaseFavorites
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $content
 * @property string $type
 * 
 * @method integer   getUserId()  Returns the current record's "user_id" value
 * @method string    getContent() Returns the current record's "content" value
 * @method string    getType()    Returns the current record's "type" value
 * @method Favorites setUserId()  Sets the current record's "user_id" value
 * @method Favorites setContent() Sets the current record's "content" value
 * @method Favorites setType()    Sets the current record's "type" value
 * 
 * @package    epg2.0
 * @subpackage model
 * @author     Huan Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFavorites extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('favorites');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('content', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('type', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}