<?php

/**
 * BaseProgramTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $p_id
 * @property integer $wiki_id
 * @property string $name
 * @property string $time
 * @property ProgramIndex $ProgramIndex
 * 
 * @method integer         getPId()          Returns the current record's "p_id" value
 * @method integer         getWikiId()       Returns the current record's "wiki_id" value
 * @method string          getName()         Returns the current record's "name" value
 * @method string          getTime()         Returns the current record's "time" value
 * @method ProgramIndex    getProgramIndex() Returns the current record's "ProgramIndex" value
 * @method ProgramTemplate setPId()          Sets the current record's "p_id" value
 * @method ProgramTemplate setWikiId()       Sets the current record's "wiki_id" value
 * @method ProgramTemplate setName()         Sets the current record's "name" value
 * @method ProgramTemplate setTime()         Sets the current record's "time" value
 * @method ProgramTemplate setProgramIndex() Sets the current record's "ProgramIndex" value
 * 
 * @package    epg2.0
 * @subpackage model
 * @author     Huan Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProgramTemplate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('program_template');
        $this->hasColumn('p_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('wiki_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('time', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProgramIndex', array(
             'local' => 'p_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}