tinyMCE.addI18n('en.searchreplace_dlg',{
searchnext_desc:"查找文本",
notfound:"没有找到改文本",
search_title:"查找",
replace_title:"查找/替换",
search_desc:"查找",
allreplaced:"替换完成",
findwhat:"查找内容",
replacewith:"替换为",
direction:"方向",
up:"向上",
down:"向下",
mcase:"区分大小写",
findnext:"查找下一个",
replace:"替换",
replaceall:"全部替换",
search:"查找"
});