<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/09/10 08:16:15
sfConfig::add(array(
  'app_httpsqs_host' => '172.31.200.62',
  'app_httpsqs_port' => 1218,
  'app_httpsqs_auth' => 'epgpass',
  'app_httpsqs_charset' => 'utf-8',
  'app_cpgPortal_url' => 'http://172.20.224.146:8086/nj-portal/oss/getNScreenPlayUrl',
  'app_cpgPortal_username' => 'bokonguser',
  'app_cpgPortal_password' => 12345678,
  'app_cpgFtp_host' => '172.20.224.235',
  'app_cpgFtp_port' => 21,
  'app_cpgFtp_username' => 'timeshift',
  'app_cpgFtp_password' => 'timeshift123',
  'app_linkQuery_center' => 'http://172.31.179.235:8880/SearchService/ContentLinksQuery',
  'app_statsQuery_biz' => 'http://172.31.6.27:8080/hems/servlet/BizStatsQuery',
  'app_recommend_vodWho' => 'center',
  'app_recommend_liveWho' => 'tcl',
  'app_recommend_tclUrl' => 'http://172.31.200.20:8080/urec/api/v2/interface',
  'app_recommend_centerUrl' => 'http://172.20.224.181:9090/ie/interface',
  'app_recommend_tongzhouUrl' => 'http://172.31.177.250:8080/recommand/recommand/epgAction.action',
  'app_cmsCenter_importUrl' => 'http://172.31.155.22:9080/core/ContentLinksQuery.do',
  'app_cmsCenter_bkjson' => 'http://172.31.183.230:8080/icms/content',
  'app_cmsCenter_bkjsonVod' => 'http://172.31.183.10:8080/icms/content',
  'app_epgJson_ip' => '172.31.198.32',
  'app_epgJson_username' => 'huanwang',
  'app_epgJson_password' => 'huanwang',
  'app_img_url' => 'http://172.31.139.17:81/',
  'app_epghuan_url' => 'http://www.epg.huan.tv/json',
  'app_epghuan_posturl' => 'http://www.epg.huan.tv/inject',
  'app_epghuan_apikey' => 'FBCECY2E',
  'app_epghuan_secretkey' => '9ef2977d62f85681eae90788b13678af',
  'app_search_url' => 'http://172.31.139.19/was5/web/search',
  'app_exec_path' => '/bin/php /www/newepg/symfony',
  'app_DataWarehouse_ip' => '172.31.143.126',
  'app_DataWarehouse_username' => 'njepg',
  'app_DataWarehouse_password' => 'njepg',
  'app_centerFtp_host' => '172.20.225.218',
  'app_centerFtp_port' => 21,
  'app_centerFtp_username' => 'bokongUser',
  'app_centerFtp_password' => 'bokongUser',
  'app_commonFtp_host' => '172.31.201.123',
  'app_commonFtp_port' => 21,
  'app_commonFtp_username' => 'writeepg',
  'app_commonFtp_password' => 'epg123456',
  'app_admin_credentials' => array (
  'system' => 
  array (
    'label' => '系统管理',
    'credential' => 
    array (
      'admin' => '权限管理',
      'attachments_pre' => '文件审核',
      'media' => '文件管理',
      'setting_recommend' => '推荐系统切换',
      'setting_page' => '应急页面切换',
      'setting_autohidden' => '自动隐藏时间设置',
      'crontabLog' => '计划任务日志',
      'queueLog' => '消息队列失败日志',
    ),
  ),
  'words' => 
  array (
    'label' => '敏感词',
    'credential' => 
    array (
      'words' => '敏感词',
      'setting_wordsCheck' => '敏感词审核状态',
      'wordsLog' => '敏感词日志',
      'wordsWiki' => '检查所有wiki',
    ),
  ),
  'class' => 
  array (
    'label' => '分类管理',
    'credential' => 
    array (
      'tv_station' => '电视台管理',
      'channel' => '电视频道管理',
      'spservice' => 'NIT管理',
    ),
  ),
  'count' => 
  array (
    'label' => '数据统计',
    'credential' => 
    array (
      'count_videoCount' => '上线电视剧错误日志',
      'count_cdiCount' => '上下线影片数量统计',
      'count_vodCount' => '影片点播量统计',
      'count_injectCount' => 'ADI文件入库统计',
      'count_programCount' => '节目统计',
      'count_wikiCount' => '维基统计',
      'count_fileCount' => '图片统计',
      'count_liveLog' => '直播频道点击统计',
    ),
  ),
  'content' => 
  array (
    'label' => '内容管理',
    'credential' => 
    array (
      'program' => '电视节目管理',
      'program_week' => '大网节目管理',
      'cpg' => '回看节目管理',
      'wiki' => '维基(媒资)管理',
      'wiki_unaudited' => '未审核维基',
      'video' => '视频管理',
      'count_epgLog' => 'EPG发送频道查询',
    ),
  ),
  'recommand' => 
  array (
    'label' => '推荐管理',
    'credential' => 
    array (
      'wiki_recommend' => '推荐维基管理',
      'channel_recommend' => '频道推荐管理',
      'recommand_fix' => '固定点播推荐',
    ),
  ),
  'adicdi' => 
  array (
    'label' => '固定接入',
    'credential' => 
    array (
      'content_inject' => 'CMS内容导入',
      'content_import' => 'CMS内容处理',
      'content_cdi' => '上下线内容查看',
    ),
  ),
  'check' => 
  array (
    'label' => '系统监测',
    'credential' => 
    array (
      'check_interface' => '接口监测',
      'check_log' => '接口监测日志',
      'check_epgbak' => '回看节目单监测',
      'check_epg' => '欢网节目单监测',
      'check_epgWeek' => '大网节目单监测',
      'check_epgBochu' => '以播出为准节目单监测',
    ),
  ),
  'other' => 
  array (
    'label' => '其他管理',
    'credential' => 
    array (
      'spservice_getSpLogo' => '查看所有台标',
      'post' => '测试推荐接口',
      'memadmin' => '管理memcache',
      'memcache' => '查看memcache',
      'synfile' => '单图片同步',
    ),
  ),
),
));
