<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version36 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user_ext', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'user_key' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '50',
             ),
             'user_value' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '10000',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('user', 'city');
        $this->addColumn('user', 'avatar', 'string', '100', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('user_ext');
        $this->addColumn('user', 'city', 'string', '10', array(
             'notnull' => '1',
             ));
        $this->removeColumn('user', 'avatar');
    }
}