<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('tv_station', 'is_common');
    }

    public function down()
    {
        $this->addColumn('tv_station', 'is_common', 'integer', '1', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }
}