<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version31 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('program_tag', 'time', 'time', '25', array(
             ));
        $this->addColumn('program_tag', 'date', 'date', '25', array(
             ));
        $this->addColumn('program_tag', 'channel_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('program_tag', 'time');
        $this->removeColumn('program_tag', 'date');
        $this->removeColumn('program_tag', 'channel_id');
    }
}