<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version43 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('channel', 'logo', 'string', '100', array(
             'notnull' => '',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('channel', 'logo');
    }
}