<?php

/**
 * BaseAdmin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $username
 * @property string $password
 * @property string $name
 * @property string $phone
 * @property boolean $status
 * @property string $email
 * @property string $last_login_ip
 * @property timestamp $last_login_at
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $AdminAuth
 * 
 * @method string              getUsername()      Returns the current record's "username" value
 * @method string              getPassword()      Returns the current record's "password" value
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getPhone()         Returns the current record's "phone" value
 * @method boolean             getStatus()        Returns the current record's "status" value
 * @method string              getEmail()         Returns the current record's "email" value
 * @method string              getLastLoginIp()   Returns the current record's "last_login_ip" value
 * @method timestamp           getLastLoginAt()   Returns the current record's "last_login_at" value
 * @method timestamp           getCreatedAt()     Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()     Returns the current record's "updated_at" value
 * @method Doctrine_Collection getAdminAuth()     Returns the current record's "AdminAuth" collection
 * @method Admin               setUsername()      Sets the current record's "username" value
 * @method Admin               setPassword()      Sets the current record's "password" value
 * @method Admin               setName()          Sets the current record's "name" value
 * @method Admin               setPhone()         Sets the current record's "phone" value
 * @method Admin               setStatus()        Sets the current record's "status" value
 * @method Admin               setEmail()         Sets the current record's "email" value
 * @method Admin               setLastLoginIp()   Sets the current record's "last_login_ip" value
 * @method Admin               setLastLoginAt()   Sets the current record's "last_login_at" value
 * @method Admin               setCreatedAt()     Sets the current record's "created_at" value
 * @method Admin               setUpdatedAt()     Sets the current record's "updated_at" value
 * @method Admin               setAdminAuth()     Sets the current record's "AdminAuth" collection
 * 
 * @package    epg2.0
 * @subpackage model
 * @author     Huan Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdmin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('admin');
        $this->hasColumn('username', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('password', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('name', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('phone', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('last_login_ip', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('last_login_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'length' => 25,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AdminAuth', array(
             'local' => 'id',
             'foreign' => 'admin_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}