<?php

/**
 * BaseUserLiving
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $channel
 * @property integer $isliving
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method integer    getUserId()     Returns the current record's "user_id" value
 * @method string     getChannel()    Returns the current record's "channel" value
 * @method integer    getIsliving()   Returns the current record's "isliving" value
 * @method timestamp  getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp  getUpdatedAt()  Returns the current record's "updated_at" value
 * @method UserLiving setId()         Sets the current record's "id" value
 * @method UserLiving setUserId()     Sets the current record's "user_id" value
 * @method UserLiving setChannel()    Sets the current record's "channel" value
 * @method UserLiving setIsliving()   Sets the current record's "isliving" value
 * @method UserLiving setCreatedAt()  Sets the current record's "created_at" value
 * @method UserLiving setUpdatedAt()  Sets the current record's "updated_at" value
 * 
 * @package    epg2.0
 * @subpackage model
 * @author     Huan Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserLiving extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('userliving');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('channel', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('isliving', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'length' => 25,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}