<?php

/**
 * BaseAttachmentCategorys
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $parent_id
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method integer             getParentId()  Returns the current record's "parent_id" value
 * @method AttachmentCategorys setName()      Sets the current record's "name" value
 * @method AttachmentCategorys setParentId()  Sets the current record's "parent_id" value
 * 
 * @package    epg2.0
 * @subpackage model
 * @author     Huan Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAttachmentCategorys extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attachment_categorys');
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}