<?php

/**
 * BaseChannelRecommend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $channel_code
 * @property string $wiki_id
 * @property string $title
 * @property string $pic
 * @property string $playtime
 * @property string $remark
 * @property integer $sort
 * @property integer $publish
 * @property bigint $tongbu_id
 * 
 * @method string           getChannelCode()  Returns the current record's "channel_code" value
 * @method string           getWikiId()       Returns the current record's "wiki_id" value
 * @method string           getTitle()        Returns the current record's "title" value
 * @method string           getPic()          Returns the current record's "pic" value
 * @method string           getPlaytime()     Returns the current record's "playtime" value
 * @method string           getRemark()       Returns the current record's "remark" value
 * @method integer          getSort()         Returns the current record's "sort" value
 * @method integer          getPublish()      Returns the current record's "publish" value
 * @method bigint           getTongbuId()     Returns the current record's "tongbu_id" value
 * @method ChannelRecommend setChannelCode()  Sets the current record's "channel_code" value
 * @method ChannelRecommend setWikiId()       Sets the current record's "wiki_id" value
 * @method ChannelRecommend setTitle()        Sets the current record's "title" value
 * @method ChannelRecommend setPic()          Sets the current record's "pic" value
 * @method ChannelRecommend setPlaytime()     Sets the current record's "playtime" value
 * @method ChannelRecommend setRemark()       Sets the current record's "remark" value
 * @method ChannelRecommend setSort()         Sets the current record's "sort" value
 * @method ChannelRecommend setPublish()      Sets the current record's "publish" value
 * @method ChannelRecommend setTongbuId()     Sets the current record's "tongbu_id" value
 * 
 * @package    epg2.0
 * @subpackage model
 * @author     Huan Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChannelRecommend extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('channel_recommend');
        $this->hasColumn('channel_code', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('wiki_id', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('title', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('pic', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('playtime', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('remark', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sort', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 8,
             ));
        $this->hasColumn('publish', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('tongbu_id', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'default' => 0,
             'length' => 20,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}