<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ip', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'ip1' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'ip2' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'province' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '10',
             ),
             'city' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '10',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'MyISAM',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('ip');
    }
}