<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version41 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('program', 'fulltime', 'datetime');
    }

    public function down()
    {
        $this->removeColumn('program', 'fulltime');
    }
}