<?php

/**
 * Admin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    epg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Admin extends BaseAdmin
{
    public $auths = array();
    public $change_auth = false;

    public function __call($method, $arguments) {
        $method_str = strtolower(substr($method, 3, -4));
        $method_type = strtolower(substr($method, 0, 3));
        
        if (strpos($method, 'Auth')) {
            if ($method_type == 'set') {
                $this->setAuths($arguments[0]);
            } else if ($method_type == 'get') {
                return $this->getAuths($key);
            }
        } else {
            return parent::__call($method, $arguments);
        }
    }
    
    /**
     * 保存密码
     * 参数为空不处理,否则md5后保存
     * @param <string> $password
     */
    public function  setPassword($password) {
        if(strlen($password)) $this->_set ('password', md5($password));
    }

    public function setAuths($auths) {
        $this->change_auth = true;
        if($auths) {
            $this->auths = array_merge($this->auths, $auths);
        }
    }

    public function save(Doctrine_Connection $conn = null) {
        parent::save();

        //设置权限
        if($this->change_auth == true) {
            Doctrine::getTable('AdminAuth')->setAuths($this->_get('id'), $this->auths);
        }
    }

}