<?php

/**
 * UserExtTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserExtTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserExtTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserExt');
    }
}