<?php

/**
 * UserLivingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserLivingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserLivingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserLiving');
    }
    //根据频道得到人数
	public function getTotalnum($channel)
	{
	    /*
		$num = $this->createQuery("c")
            ->select('count(*) as num')
			->where('c.channel = ?',$channel)
            ->andWhere('c.isliving=?',1)
			->fetchOne()
            ->toArray();
        return $rs['num'];
        */
		$num = $this->createQuery()
			->where('channel = ?',$channel)
            ->andWhere('isliving=?',1)
            ->count();
        return $num;
	}
}