<?php

/**
 * AttachmentCategorys
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    epg
 * @subpackage model
 * @author     Mozi Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AttachmentCategorys extends BaseAttachmentCategorys
{
    protected function getChildCategorys()
    {
         return Doctrine::getTable('AttachmentCategorys')->createQuery()->where('parent_id = ?',$this->getId())->execute();
    }

    public function isParentCategory()
    {
        $childCategorys = $this->getChildCategorys();
        $categorys = $childCategorys->count();
        if($categorys > 0)
        {
            return $childCategorys;
        }else{
            return false;
        }
    }

}