<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('wiki_tag', 'program_id');
        $this->addColumn('wiki_tag', 'wiki_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->addColumn('wiki_tag', 'program_id', 'integer', '8', array(
             ));
        $this->removeColumn('wiki_tag', 'wiki_id');
    }
}