<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version32 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('program_tag', 'program_tag_channel_id_channel_id', array(
             'name' => 'program_tag_channel_id_channel_id',
             'local' => 'channel_id',
             'foreign' => 'id',
             'foreignTable' => 'channel',
             ));
        $this->addIndex('program_tag', 'program_tag_channel_id', array(
             'fields' => 
             array(
              0 => 'channel_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('program_tag', 'program_tag_channel_id_channel_id');
        $this->removeIndex('program_tag', 'program_tag_channel_id', array(
             'fields' => 
             array(
              0 => 'channel_id',
             ),
             ));
    }
}