<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version30 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('program', 'wiki_id', 'integer', '8', array(
             'notnull' => '',
             'default' => '0',
             ));
        $this->changeColumn('program', 'type', 'string', '20', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}