<?php

/**
 * UserLiving
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    epg2.0
 * @subpackage model
 * @author     Huan Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserLiving extends BaseUserLiving
{

}