<?php

/**
 * ChannelRecommendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChannelRecommendTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChannelRecommendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChannelRecommend');
    }
}