<?php

/**
 * ThemeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ThemeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ThemeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Theme');
    }
    /**
     * 根据当前页数$page，每页限数量$size.查找themes
     *
     * @return object 
     * author wangnan
     */
    public static function getThemeByPageAndSize($page,$size)
    {
        $memcache = tvCache::getInstance();
        $memcache_key = md5('getThemeByPageAndSize'.",$page,$size");
        $themes = $memcache->get($memcache_key);
        if(!$themes){        
        	$offset = ($page-1)*$size;
    		$themes    = Doctrine::getTable('Theme')->createQuery()
    					->offset($offset)
    					->limit($size)
    					->where("publish= ?",1)
    					->execute();
            if($page<=3&&($size==8||$size==10))            
                $memcache->set($memcache_key,$themes);
        }            
		return $themes;
    }
    /**
     * 查找所有theme
     *
     * @return object 
     * author wangnan
     */
    public static function getThemes()
    {
        $memcache = tvCache::getInstance();
        $memcache_key = md5('getThemes');
        $themes = $memcache->get($memcache_key);
        if(!$themes){           
    		$themes    = Doctrine::getTable('Theme')->createQuery()
    					->where("publish= ?",1)
    					->execute();
            $memcache->set($memcache_key,$themes);            
        }            
		return $themes;
    }    
    
}