<?php

/**
 * Theme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    epg
 * @subpackage model
 * @author     Mozi Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Theme extends BaseTheme
{
	public function getAllItem()
	{
		$items = Doctrine_Core::getTable('ThemeItem')->createQuery('a')->where('a.theme_id = ?', $this->getId())->execute();		
		$mongo = sfContext::getInstance()->getMondongo();
		$WikiRepository = $mongo->getRepository('Wiki');
		foreach($items as $key => $item) {
			$wiki = $WikiRepository->findOneById(new MongoId($item->getWikiId()));
            if($wiki){
                $title=$wiki->getTitle();
                $displayname=$wiki->getDisplayName();
                $coverurl=$wiki->getCoverurl();
            }else{
                $title='';
                $displayname='';
                $coverurl='';
            }
			$item->setTitle($title);
			$item->setDisplayName($displayname);
			$item->setCoverurl($coverurl);
			$items[$key] = $item;
		}
		return $items;
	}

}
