<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version14 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('channel', 'config', 'string', '4000', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('channel', 'config');
    }
}