<?php

/**
 * BaseAdminAuth
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $admin_id
 * @property string $credential
 * @property Admin $Admin
 * 
 * @method integer   getAdminId()    Returns the current record's "admin_id" value
 * @method string    getCredential() Returns the current record's "credential" value
 * @method Admin     getAdmin()      Returns the current record's "Admin" value
 * @method AdminAuth setAdminId()    Sets the current record's "admin_id" value
 * @method AdminAuth setCredential() Sets the current record's "credential" value
 * @method AdminAuth setAdmin()      Sets the current record's "Admin" value
 * 
 * @package    epg2.0
 * @subpackage model
 * @author     Huan Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdminAuth extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('admin_auth');
        $this->hasColumn('admin_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('credential', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin', array(
             'local' => 'admin_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}