<?php

/**
 * BaseTvStation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $parent_id
 * @property string $name
 * @property integer $sort
 * @property integer $publish
 * @property string $code
 * @property TvStation $TvStation
 * @property Doctrine_Collection $Channel
 * 
 * @method integer             getParentId()  Returns the current record's "parent_id" value
 * @method string              getName()      Returns the current record's "name" value
 * @method integer             getSort()      Returns the current record's "sort" value
 * @method integer             getPublish()   Returns the current record's "publish" value
 * @method string              getCode()      Returns the current record's "code" value
 * @method TvStation           getTvStation() Returns the current record's "TvStation" value
 * @method Doctrine_Collection getChannel()   Returns the current record's "Channel" collection
 * @method TvStation           setParentId()  Sets the current record's "parent_id" value
 * @method TvStation           setName()      Sets the current record's "name" value
 * @method TvStation           setSort()      Sets the current record's "sort" value
 * @method TvStation           setPublish()   Sets the current record's "publish" value
 * @method TvStation           setCode()      Sets the current record's "code" value
 * @method TvStation           setTvStation() Sets the current record's "TvStation" value
 * @method TvStation           setChannel()   Sets the current record's "Channel" collection
 * 
 * @package    epg2.0
 * @subpackage model
 * @author     Huan Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTvStation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tv_station');
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('sort', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('publish', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('code', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TvStation', array(
             'local' => 'parent_id',
             'foreign' => 'id'));

        $this->hasMany('Channel', array(
             'local' => 'id',
             'foreign' => 'tv_station_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}