<?php

/**
 * BaseAttention
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $pid
 * 
 * @method integer   getUserId()  Returns the current record's "user_id" value
 * @method integer   getPid()     Returns the current record's "pid" value
 * @method Attention setUserId()  Sets the current record's "user_id" value
 * @method Attention setPid()     Sets the current record's "pid" value
 * 
 * @package    epg2.0
 * @subpackage model
 * @author     Huan Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAttention extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attention');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('pid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}