<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/05/23 11:20:04
sfConfig::add(array(
  'app_sphinxsearch_host' => '192.168.1.32',
  'app_sphinxsearch_port' => 9312,
  'app_sphinxsearch_limits' => 10,
  'app_photo_type' => 'MogilefsStorage',
  'app_photo_config' => array (
  'hosts' => '172.30.95.159:7001',
  'domain' => '5itv',
  'class' => 'image',
),
  'app_static_url' => 'http://epgimg.henancatv.com/',
  'app_huan_uc_url' => 'http://61.145.165.154:8080/uc/json',
  'app_lct_server_url' => 'http://192.168.10.71:8080/lct-server/',
  'app_memcache_servers' => array (
  'config_one' => 
  array (
    'host' => '172.30.95.160',
    'port' => 11211,
  ),
),
  'app_memcache_compression' => 0,
  'app_memcache_lefttime' => 7200,
  'app_php_path' => '/hwdata/php/bin/',
  'app_project_path' => '/hwdata/www/hnepg/',
));
