<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/05/23 11:20:04
$this->security = array (
  'home' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
