<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/05/23 12:00:01
sfConfig::add(array(
  'app_admin_credentials' => array (
  'admin' => 
  array (
    'label' => '管理',
    'credential' => 
    array (
      'admin_show' => '查看',
      'admin_new' => '新增',
      'admin_edit' => '编辑',
      'admin_del' => '删除',
    ),
  ),
  'channel' => 
  array (
    'label' => '频道',
    'credential' => 
    array (
      'channel_show' => '查看',
      'channel_new' => '新增',
      'channel_edit' => '编辑',
      'channel_del' => '删除',
    ),
  ),
  'program' => 
  array (
    'label' => '节目单',
    'credential' => 
    array (
      'program_show' => '查看',
      'program_new' => '新增',
      'program_edit' => '编辑',
      'program_del' => '删除',
      'program_publish' => '发布',
    ),
  ),
  'program_index' => 
  array (
    'label' => '节目标题',
    'credential' => 
    array (
      'program_index_show' => '查看',
      'program_index_new' => '新增',
      'program_index_edit' => '编辑',
      'program_index_del' => '删除',
    ),
  ),
  'program_ext' => 
  array (
    'label' => '推荐管理',
    'credential' => 
    array (
      'program_ext_show' => '查看',
      'program_ext_new' => '新增',
      'program_ext_edit' => '编辑',
      'program_ext_del' => '删除',
    ),
  ),
  'program_template' => 
  array (
    'label' => '节目模板',
    'credential' => 
    array (
      'program_template_show' => '查看',
      'program_template_new' => '新增',
      'program_template_edit' => '编辑',
      'program_template_del' => '删除',
    ),
  ),
  'tags' => 
  array (
    'label' => '标签',
    'credential' => 
    array (
      'tags_show' => '查看',
      'tags_new' => '新增',
      'tags_edit' => '编辑',
      'tags_del' => '删除',
    ),
  ),
  'tag_relationships' => 
  array (
    'label' => '标签关联',
    'credential' => 
    array (
      'tags_show' => '查看',
      'tags_new' => '新增',
      'tags_edit' => '编辑',
      'tags_del' => '删除',
    ),
  ),
  'tv_station' => 
  array (
    'label' => '电视台',
    'credential' => 
    array (
      'tv_station_show' => '查看',
      'tv_station_new' => '新增',
      'tv_station_edit' => '编辑',
      'tv_station_del' => '删除',
    ),
  ),
  'wiki' => 
  array (
    'label' => '维基',
    'credential' => 
    array (
      'wiki_show' => '查看',
      'wiki_new' => '新增',
      'wiki_edit' => '编辑',
      'wiki_del' => '删除',
    ),
  ),
),
  'app_photo_type' => 'MogilefsStorage',
  'app_photo_config' => array (
  'hosts' => '172.30.95.159:7001',
  'domain' => '5itv',
  'class' => 'image',
),
  'app_static_url' => 'http://epgimg.henancatv.com/',
  'app_huan_uc_url' => 'http://61.145.165.154:8080/uc/json',
  'app_lct_server_url' => 'http://192.168.10.71:8080/lct-server/',
  'app_memcache_servers' => array (
  'config_one' => 
  array (
    'host' => '172.30.95.160',
    'port' => 11211,
  ),
),
  'app_memcache_compression' => 0,
  'app_memcache_lefttime' => 7200,
  'app_php_path' => '/hwdata/php/bin/',
  'app_project_path' => '/hwdata/www/hnepg/',
));
