<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/05/23 12:00:01

return array(
'master' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=172.30.95.155;port=3306;dbname=epg',
  'username' => 'epg',
  'password' => 'epgpass',
  'name' => 'master',
)),

'mondongo' => new sfMondongoDatabase(array (
  'server' => 'mongodb://epg:epgpass@172.30.95.157:27017',
  'database' => 'epg',
  'name' => 'mondongo',
)),);
