<?php

/**
 * ThemeItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ThemeItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ThemeItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ThemeItem');
    }
    /**
     * 根据专题ID获取items.
     *	
     * @return object 
     * author wangnan
     */    
    public static function getItemsByThemeId($tid)
    {
		$items    = Doctrine::getTable('ThemeItem')->createQuery()
					->where('theme_id=?', $tid)
					->execute();
		return $items;
                    
    }    
}