tinyMCE.addI18n('en.advanced',{
style_select:"Styles",
font_size:"文本大小",
fontdefault:"Font family",
block:"Format",
paragraph:"Paragraph",
div:"Div",
address:"Address",
pre:"Preformatted",
h1:"Heading 1",
h2:"Heading 2",
h3:"Heading 3",
h4:"Heading 4",
h5:"Heading 5",
h6:"Heading 6",
blockquote:"Blockquote",
code:"Code",
paste:"",
samp:"Code sample",
dt:"Definition term ",
dd:"Definition description",
bold_desc:"加粗 (Ctrl+B)",
italic_desc:"斜体 (Ctrl+I)",
underline_desc:"下划线 (Ctrl+U)",
striketrough_desc:"删除线",
justifyleft_desc:"左对齐",
justifycenter_desc:"居中",
justifyright_desc:"右对齐",
justifyfull_desc:"Align full",
bullist_desc:"无序列表",
numlist_desc:"有序列表",
outdent_desc:"Outdent",
indent_desc:"Indent",
undo_desc:"撤销 (Ctrl+Z)",
redo_desc:"重做 (Ctrl+Y)",
link_desc:"Insert/edit link",
unlink_desc:"Unlink",
image_desc:"Insert/edit image",
cleanup_desc:"Cleanup messy code",
code_desc:"编辑HTML源代码",
sub_desc:"Subscript",
sup_desc:"Superscript",
hr_desc:"Insert horizontal ruler",
removeformat_desc:"清除样式",
custom1_desc:"Your custom description here",
forecolor_desc:"选择文字颜色",
backcolor_desc:"选择背景颜色",
charmap_desc:"Insert custom character",
visualaid_desc:"Toggle guidelines/invisible elements",
anchor_desc:"Insert/edit anchor",
cut_desc:"剪切",
copy_desc:"复制",
paste_desc:"粘贴",
image_props_desc:"Image properties",
newdocument_desc:"New document",
help_desc:"帮助",
blockquote_desc:"Blockquote",
clipboard_msg:"Copy/Cut/Paste is not available in Mozilla and Firefox.\r\nDo you want more information about this issue?",
path:"Path",
newdocument:"Are you sure you want clear all contents?",
toolbar_focus:"Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X",
more_colors:"More colors"
});