<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('wiki_ext', 'parent', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('wiki_ext', 'parent');
    }
}