<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version19 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('favorites', 'pid');
        $this->addColumn('favorites', 'content', 'string', '50', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('favorites', 'pid', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->removeColumn('favorites', 'content');
    }
}