<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version33 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('program', 'type');
    }

    public function down()
    {
        $this->addColumn('program', 'type', 'string', '20', array(
             'notnull' => '1',
             ));
    }
}