<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version39 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('wiki_ext', 'wiki_key', 'string', '50', array(
             ));
    }

    public function down()
    {

    }
}