<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version40 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('attachments', 'file_type');
        $this->addColumn('attachments', 'file_key', 'string', '500', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('attachments', 'file_type', 'string', '100', array(
             'notnull' => '1',
             ));
        $this->removeColumn('attachments', 'file_key');
    }
}