<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version42 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('attachments', 'thumb', 'string', '4000', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->changeColumn('attachment_categorys', 'name', 'string', '250', array(
             'notnull' => '1',
             ));
        $this->changeColumn('attachments', 'source_name', 'string', '250', array(
             'notnull' => '1',
             ));
        $this->changeColumn('attachments', 'file_name', 'string', '250', array(
             'notnull' => '1',
             ));
        $this->changeColumn('attachments', 'file_key', 'string', '250', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('attachments', 'thumb');
    }
}