<?php

/**
 * ProgramIndex
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    epg
 * @subpackage model
 * @author     Mozi Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProgramIndex extends BaseProgramIndex
{

    public function  delete(Doctrine_Connection $conn = null)
    {

        //删除program
        $tv = Doctrine::getTable('ProgramTemplate')->findBy('p_id',$this->getId());
        foreach ($tv as $rs)
        {
            $rs->delete();
        }
        parent::delete($conn);
    }
}