<?php

/**
 * TvStation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    epg
 * @subpackage model
 * @author     Mozi Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TvStation extends BaseTvStation
{
    /**
     * 获取此电视台下所有频道列表
     * @return <type>
     * @author zhigang
     */
    public function getChannels() {
        $channels = Doctrine::getTable("Channel")
                ->getChannlesWithTvStation($this->getId());

        return $channels;
    }
    
    /**
     * 删除关联
     * @param Doctrine_Connection $conn
     * @author Ward
     */
    public function  delete(Doctrine_Connection $conn = null) {
        $tv = Doctrine::getTable('Channel')->findByTvStationId($this->getId());
        if(!empty ($tv)){
            foreach ($tv as $rs) {
                $rs->delete();
            }
        }
        parent::delete($conn);
    }
}