<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('program_bot', 'date', 'date', '25', array(
             ));
    }

    public function down()
    {

    }
}