<?php

/**
 * ChannelRecommendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChannelRecommendTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChannelRecommendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChannelRecommend');
    }
    /**
     * Returns wikis.
     *
     * @return object ChannelRecommendTable
     */
    public function getWikis($channel_code,$limit=0)
    {
        return $this->createQuery()
                ->where('channel_code = ?', $channel_code)
                ->orderBy('sort')
                ->limit($limit)
                ->execute();
    }
}