<?php

/**
 * Channel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    epg
 * @subpackage model
 * @author     Mozi Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Channel extends BaseChannel
{
    /**
     * 获取当前平道正在播出的节目名称
     * @return <string>
     * @author pjl
     */
    public function getLiveProgramName() {
        $name = '';
        $program = $this->getNowPrograms(1);
        if($program[0]) {
            $name = $program[0]->getName();
        }
        return $name;
    }
    
    function getStatus()
    {
        if($this->getPublish())
        {
            return '已发布';
        }
        return '未发布';
    }

    public function getLink()
    {
        return '<a href="">'.$this->getTvStation().'</a>';
    }

    /**
     * 获取频道图标地址
     * @return string
     * @author zhigang
     */
    public function getLogoUrl() {
        sfContext::getInstance()->getConfiguration()->loadHelpers(array('GetFileUrl','Asset'));
        $logo = $this->getLogo();
        if (strlen($logo)) {
            return file_url($logo);
        } else {
            return false;
        }
    }

    public function  delete(Doctrine_Connection $conn = null)
    {
                       
        //删除缓存
        $memcache = tvCache::getInstance();
        $memcache_key = $this->getCode();
        if($memcache->has($memcache_key)){
            $memcache->delete($memcache_key);
        }
//        //删除program 暂时注释
//       $mongo = sfContext::getInstance()->getMondongo();
//       $program_mongo = $mongo->getRepository("Program");
//       $programs = $program_mongo->getProgramsByCode($this->getCode());
//       foreach ($programs as $program){
//           $program->delete();
//       }
//       $program->delete();
       parent::delete($conn);
    }


    /**
     *
     * @param Doctrine_Connection $conn
     * @author ly
     */
    public function save(Doctrine_Connection $conn = null) {
        //删除缓存
        $memcache = tvCache::getInstance();
        $memcache_key = $this->getCode();
        if($memcache->has($memcache_key)){
            $memcache->delete($memcache_key);
        }
        parent::save($conn);
    }

    public function getDayPrograms($date = '') {
        $channel_code = $this->getCode();

        $mongo = sfContext::getInstance()->getMondongo();
        return $mongo->getRepository('Program')->getDayPrograms($channel_code, $date);
    }
    
    /**
     * 获得当天有wiki的节目
     */
    public function getDayProgramsWiki($date='') {
        $channel_code = $this->getCode();

        $mongo = sfContext::getInstance()->getMondongo();
        return $mongo->getRepository('Program')->getDayProgramsWiki($channel_code, $date);
    }

    /**
     * 获取今天正在或将要播出的节目
     * @author ly
     */
    public function getNowPrograms($limit = 5){
        $channel_code = $this->getCode();
        $mongo = sfContext::getInstance()->getMondongo();
        $program_repo = $mongo->getRepository("Program");
        return $program_repo->find(array("query" =>
                array("channel_code" => $channel_code,
                      "end_time" => array('$gte' => new MongoDate()),
                      ),
                'sort' => array('start_time' => 1),
                'limit' => $limit)
            );

    }

    /**
     * 获取一条正在播出的节目要求拥有 Wiki
     * @return <type>
     * @author luren
     */
    public function getOneNowProgram() {
        $mongo = sfContext::getInstance()->getMondongo();
        $program_repos = $mongo->getRepository("Program");
        $now = new MongoDate();
        
        return $program_repos->findOne(
                    array(
                        'query' => array(
                            "channel_code" => $this->getCode(),
                            'start_time' => array('$lte' => $now),
                            'end_time' => array('$gte' => $now),
                            'wiki_id' => array('$exists' => true)
                            )
                        )
                );
    }
}


