<?php

/**
 * Tags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    epg
 * @subpackage model
 * @author     Mozi Tek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tags extends BaseTags
{
    /**
     * 删除标签关联
     * @param Doctrine_Connection $conn
     * @return void
     * @author Ward
     */
    /* 
    public function  delete(Doctrine_Connection $conn = null) {
        //删除wiki_ext
        $tv = Doctrine::getTable('ProgramTag')->findByTagId($this->getId());
        foreach ($tv as $rs)
        {
            $rs->delete();
        }
        parent::delete($conn);
    }
    */
}
